config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :cart_items
  resources :carts
  resources :item_attachments

  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'home#index'

  get '/messages/inbox' => 'messages#inbox', as: 'inbox'
  get '/messages/sentbox' => 'messages#sentbox', as: 'sentbox'
  get '/messages/trash' => 'messages#trash', as: 'trash'
  get '/messages/new' => 'messages#new', as: 'compose'
  get '/messages/show' => 'messages#show', as: 'show'
  post '/messages/inbox' => 'messages#inbox'
  post '/messages/sentbox' => 'messages#sentbox'
  post '/messages/new' => 'messages#new'
  post '/messages/create' => 'messages#create'
  post '/messages/trash' => 'messages#trash'
  post '/messages/show' => 'messages#show'

  match '/destroy_image' => 'items#destroyImage', :as => 'destroyImage', via: [:get, :post]

  mount Commontator::Engine => '/commontator'

match ':controller(/:action(/:id))', :via  => [:get, :post , :delete]
  

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def inbox
    # checks if the current user is logged in or not, if not, he/she is redirected to the signin page
    if current_user == nil
      redirect_to new_user_session_path
    end
  end

  def sentbox
    # same as inbox... mainly for security reasons and to avoid errors
    if current_user == nil
      redirect_to new_user_session_path
    end
  end

  def send_trash
    # retreives the message ID passed from inbox view and sends it to trash
    @message = current_user.received_messages.find(params[:m_id])
    @message.mark_as_read
    current_user.delete_message(@message)
    redirect_to trash_path
  end

  def create
    # on sending the message, the controller checks if the recepient exists, if he/she does exist, the message is sent
    # else the page is rendered with a flash notice telling the current user that this user doesnt exist
    @receiver = User.find_by(uname: params[:compose][:user])

    if @receiver == nil
      flash.keep[:notice] = 'No User exist with that username'
      redirect_to compose_path
    else
      current_user.send_message(@receiver, params[:compose][:subject], params[:compose][:body])
      redirect_to inbox_path
    end
  end

  def show
    # this method only marks the message as read
    @m_id = params[:m_id]
    current_user.received_messages.find(params[:m_id]).open
  end

  def reply
    # calls on the reply function to reply the message given to the sending user
    @body = params[:reply][:body]
    @message = current_user.received_messages.find(params[:r_id])
    current_user.reply_to(@message, params[:r_sub], params[:reply][:r_body])
    redirect_to inbox_path
  end

end

app/views/messages/inbox.html.erb
<!-- <h1>Messages#inbox</h1> -->

<div class ="h1"> <h1> <%= current_user.fname %>'s Inbox </h1></div>
<div class = "buttons">
	<div><%= button_to 'Compose New', compose_path , :class=> 'button'%> </div> 
	<div><%= button_to 'Sent Messages', sentbox_path , :class=> 'button'%> </div>
	<div><%= button_to 'Trash', '#' , :class=> 'button'%> </div>
</div>
<table class = "table">
	<tr>
		<td class = "td1">Sender</td>
		<td class = "td2">Subject</td>
		<td class = "td3">Message</td>
		<td class = "td4">Delete</td>
	</tr>
	<!-- Loop over all received messages and show sender's name then the subject then the body -->
	<% current_user.received_messages.each do |m| %>
	<tr>
		<% @current_message = m %>
		<td class = "txt">
			<%= m.from.uname  %>
		</td>
		<td class = "txt">
			<%= m.topic %>
		</td>
		<td class = "txt">
			<!-- when you press on the body u r redirected to the reply page -->
			<%= link_to m.body, {:action => 'show', :m_body => m.body, :m_id => m.id, :m_from => m.from.uname, :m_sub => m.topic}, :class => 'txt-only' %>
		</td>
		<!-- adds the delete button that calls a method to sent this message to trash -->
		<td class = "txt">
			<%= link_to 'Delete', {:action => 'send_trash', :m_id => m.id}, :class => 'txt-only' %>
		</td>

	</tr>
	<% end %>
</td>
</tr>
</table>

app/views/messages/new.html.erb
<!-- Creates a form which takes the name of the recepient, hte subject, and the message body -->
<!-- The username is still shown on top of the page and to be removed later -->
<h1 class = "p">New Message</h1>
<div class = "dialog">
	<%= form_for :compose, :url => {:action => 'create', :controller => 'messages'} do |f| %>
	<%= f.text_area :user, :placeholder => 'Reciever Name', :size => '50x1' , :class=> 'name'%>
	<br>
	<br>
	<%= f.text_area :subject, :placeholder => 'Subject', :size => '50x2' , :class=> 'sub'%>
	<br>
	<br>
	<%= f.text_area :body, :placeholder => 'Message Body', :size => '50x20' , :class=> 'body'%>
	<br>
	<br>
	<%= f.submit 'Send' , :class=> 'send'%>
	<% end %>
</div>

app/views/messages/sentbox.html.erb
<div class ="h1"> <h1> <%= current_user.fname %>'s Inbox </h1></div>
<div class = "buttons">
	<div><%= button_to 'Compose New', compose_path , :class=> 'button'%> </div> 
	<div><%= button_to 'Inbox', inbox_path , :class=> 'button'%> </div>
	<div><%= button_to 'Trash', trash_path , :class=> 'button'%> </div>
</div>
<table class = "table">
	<tr>
		<td class = "td">Recipient</td>
		<td class = "td">Subject</td>
		<td class = "td-message">Message</td>
	</tr>
	<!-- Loop over all sent messages and show recipient's name then the subject then the body -->
	<% current_user.sent_messages.each do |m| %>
	<tr>
		<% @current_message = m %>
		<td class = "txt">
			<%= m.to.uname  %>
		</td>
		<td class = "txt">
			<%= m.topic %>
		</td>
		<td class = "txt">
			<%= m.body %>
		</td>
	</tr>
	<% end %>
</td>
</tr>
</table>

app/views/messages/show.html.erb
<div class = "dialog">
	<!-- url will pass the required data to the reply function -->
	<%= form_for :reply, :url => {:action => 'reply', :controller => 'messages', :r_from => params[:m_from], :r_id => params[:m_id], :r_sub => params[:m_sub] } do |f| %>
	<textarea class = 'name'><%= params[:m_from] %></textarea>
	<br>
	<br>
	<textarea class = 'sub'>Re: <%= params[:m_sub] %></textarea>
	<br>
	<textarea class = 'sub'><%= params[:m_body] %></textarea>
	<br>
	<br>
	<%= f.text_area :r_body, :placeholder => 'Reply Body', :size => '50x20' , :class=> 'body'%>
	<br>
	<br>
	<%= f.submit 'Reply' , :class=> 'send'%>
	<% end %>
</div>

app/views/messages/trash.html.erb
<div class ="h1"> <h1> <%= current_user.fname %>'s Inbox </h1></div>
<div class = "buttons">
	<div><%= button_to 'Compose New', compose_path , :class=> 'button'%> </div> 
	<div><%= button_to 'Inbox', inbox_path , :class=> 'button'%> </div>
	<div><%= button_to 'Sentbox', sentbox_path , :class=> 'button'%> </div>
</div>
<table class = "table">
	<tr>
		<td class = "td">Recipient</td>
		<td class = "td">Subject</td>
		<td class = "td-message">Message</td>
	</tr>
	<!-- Loop over all deleted messages and show recipient's name then the subject then the body -->
	<% current_user.deleted_messages.each do |m| %>
	<tr>
		<% @current_message = m %>
		<td class = "txt">
			<%= m.to.uname  %>
		</td>
		<td class = "txt">
			<%= m.topic %>
		</td>
		<td class = "txt">
			<%= m.body %>
		</td>
	</tr>
	<% end %>
</td>
</tr>
</table>