config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :cart_items
  resources :carts
  resources :item_attachments

  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'home#index'

  get '/messages/inbox' => 'messages#inbox', as: 'inbox'
  get '/messages/sentbox' => 'messages#sentbox', as: 'sentbox'
  get '/messages/trash' => 'messages#trash', as: 'trash'
  get '/messages/new' => 'messages#new', as: 'compose'
  get '/messages/show' => 'messages#show', as: 'show'
  post '/messages/inbox' => 'messages#inbox'
  post '/messages/sentbox' => 'messages#sentbox'
  post '/messages/new' => 'messages#new'
  post '/messages/create' => 'messages#create'
  post '/messages/trash' => 'messages#trash'
  post '/messages/show' => 'messages#show'

  match '/destroy_image' => 'items#destroyImage', :as => 'destroyImage', via: [:get, :post]

  mount Commontator::Engine => '/commontator'

match ':controller(/:action(/:id))', :via  => [:get, :post , :delete]
  

end

app/models/shop.rb
class Shop < ActiveRecord::Base
	self.table_name = 'shops'

	# Associations
	belongs_to :user
	has_many :items
	has_and_belongs_to_many :followers, class_name: "User", join_table: "shops_users"

	# Scopes (Methods used in the controller)
	scope :sorted, lambda { order("shops.shop_name ASC")}
	scope :search, lambda {|query|
		where(["shop_name LIKE ?", "%#{query}%"])}
	mount_uploader :cover, ImageUploader

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    # sorted is a scope (small procedure) in the model
  	@shops = Shop.sorted
  end

  def search
    # Searches for a shop
    if !params[:query].empty?
      @shops = Shop.search(params[:query])
      @items = Item.search(params[:query])
    end
  end

  def follow
    # Adds the shop to the current user's followed shops
    @current_user = current_user
    @shop = Shop.find(params[:id])
    if !current_user.shops.include?(@shop)
    @current_user.followed_shops << @shop
    end
    flash[:notice] = "You are now following '#{@shop.shop_name}.'"
    redirect_to(:action => 'show', :id => @shop.id)
  end

  def unfollow
    # Removes the shop from the current user's followed shops
    @current_user = current_user
    @shop = Shop.find(params[:id])
    @current_user.followed_shops.delete(@shop)
    flash[:notice] = "You are no longer following '#{@shop.shop_name}.'"
    redirect_to(:action => 'show', :id => @shop.id)
  end

  def show
  	@shop = Shop.find(params[:id])
    @item = @shop.items
# Client.where("orders_count = ? AND locked = ?", params[:orders], false)
@categoryOne = @item.where("category = ")
  end

  def new
    @shop = Shop.new(:shop_name => 'default')
  end

  def create
    # Instantiate a new object - shop_params is a private methode
    @shop = Shop.new(shop_params)
    @user = current_user
    @shop.user = @user
    # Save
    if @shop.save
      # If succeeds, redirect
      redirect_to(:controller => 'profile', :action => 'myshops')
      flash[:notice] = "Shop created successfully."
    else
      # If fails, redisplay
      render('new')
    end
  end

  def edit
    # Check if current user already owns the shop in order to edit
    @shop = Shop.find(params[:id])
  end

  def update
    # Find an existing object
    @shop = Shop.find(params[:id])
    # Update the object
    if @shop.update_attributes(shop_params)
      # If succeeds, redirect
      flash[:notice] = "Shop updated successfully."
      redirect_to(:action => 'show', :id => @shop.id)
    else
      # If fails, redisplay
      render('edit')
    end
  end

  def delete
    # Check if user already owns the shop inorder to delete it
    @shop = Shop.find(params[:id])
    if current_user.shops.include?(@shop)
    else
    render 'index'
    end
  end

  def destroy
    # Find an existing object and destroy it
    shop = Shop.find(params[:id])
    if current_user.shops.include?(shop)
    	shop.destroy
    	item = shop.items
    	item.each do |item| 
    	Item.destroy(item)
    	end
    	flash[:notice] = "Shop '#{shop.shop_name}' deleted successfully."
    	redirect_to(:action => 'index')
    else 
    	render 'index'
    end
  end

  # Mass assignement parameter
  # It raises an error if :subject is not present
  private
  def shop_params
    params.require(:shop).permit(:shop_name, :shop_desc, :cover)
  end
end

app/views/shops/delete.html.erb
<div class = "form-card">
	<div class = "form-back">
		<%= link_to("<< Back", {:action => 'show', :id => @shop.id}, :class => 'form-back') %>
	</div>
	<div class = "form-title">Delete <%= @shop.shop_name %>? </div>
	<img src="<%= @shop.cover_url.to_s %>" style="width:200px;height:200px" class = "form-image">
	<%= form_for(:shop, :url => {:action => 'destroy', :id => @shop.id}) do |f| %>
	<p>Are you sure you want to permanently delete this shop?</p>

	<div>
		<%= submit_tag("Delete Shop", :class => "form-button") %>
	</div>

	<% end %>
</div>

app/views/shops/edit.html.erb
<div class = "form-card">
<div class = "form-back"><%= link_to("Back", {:action => 'index'}, :class => 'form-back') %></div>
<div class = "form-title">Edit Shop "<%= @shop.shop_name %>"</div>

<%= form_for(:shop, :url => {:action => 'update', :id => @shop.id}) do |f| %>

	<table> 
	<tr>
		<th class = 'form-attr'>Shop Name</th>
		<td><%= f.text_field(:shop_name, :class => 'form-tf') %></td>
	</tr>
	<tr>
		<th class = 'form-attr'>Shop Description</th>
		<td><%= f.text_field(:shop_desc, :class => 'form-tf') %></td>
	</tr>
	<tr>
		<th class = 'form-attr'>Shop Cover</th>
		<td><%= f.file_field(:cover, :class => 'form-upload') %></td>
	</tr>
	</table>

	<div>
		<%= submit_tag("Update Shop", :class => "form-button") %>
	</div>

	<% end %>
</div>

app/views/shops/index.html.erb
<div class="subjects index">
  
  <div>
  <div class= "pagetitle">Shops</div>
  <!-- Check if user is logged in in order to create a shop -->

    <div class = 'search-field'>
      <%= form_tag :action => 'search', :method => 'get', :class => 'search-form' do %>
        <%= text_field_tag :query, params[:query], :class => 'search-tf' %>
        <%= submit_tag "Search", :name => nil, :class => 'search-button' %>
      <% end %>    
    </div>
      <% if user_signed_in?%>
        <%= button_to("Create New Shop", {:action => 'new'}, :class => 'create-button') %>
      <%end%>
  </div>

  <!-- Shops showcase -->
  <div class = "page">
    <% @shops.each do |shop| %>
    <div class ="shop-card">
      <div class = "shop">
      <img src="<%= shop.cover_url.to_s %>" style="width:200px;height:200px"></div>
      <div><%= shop.id %></div>
      <div><%= shop.shop_name %></div>
        <div class="actions">
         <%= link_to("Show", {:action => 'show', :id => shop.id}, :class => 'actionshow') %>
        </div>
    </div>
    <% end %>
  </div>
</div>

app/views/shops/new.html.erb
<div class = "form-card">
<div class = "form-back"><%= link_to("Back", {:action => 'index'}, :class => 'form-back') %></div>
<div class = "form-title">Create New Shop</div>

<%= form_for(:shop, :url => {:action => 'create'}, :class => 'form-new') do |f| %>

	<table class = 'form-fields'> 
	<tr>
		<th class = 'form-attr'>Shop Name</th>
		<td><%= f.text_field(:shop_name, :class => 'form-tf') %></td>
	</tr>
	<tr>
		<th class = 'form-attr'>Shop Description</th>
		<td><%= f.text_area(:shop_desc, :class => 'form-ta') %></td>
	</tr>
	<tr>
		<th class = 'form-attr'>Shop Cover</th>
		<td><%= f.file_field(:cover, :class => 'form-upload') %></td>
	</tr>
	</table>
	<div >
		<%= submit_tag("Create Shop", :class => 'form-button')%>
	</div>

	<% end %>
</div>

app/views/shops/search.html.erb
<div class= "pagetitle">Search results for "<%= params[:query] %>"</div>
<div class = 'search-field2'>
      <%= form_tag :action => 'search', :method => 'get', :class => 'search-form' do %>
        <%= text_field_tag :query, params[:query], :class => 'search-tf' %>
        <%= submit_tag "Search", :name => nil, :class => 'search-button' %>
      <% end %>    
    </div>

    <!-- Shops search result -->
<div class = "page">
  <div class = "search-res">Shop results</div>
  <% if @shops != nil %>
    <% if !@shops.empty? %>
      <% @shops.each do |shop| %>
        <div class ="shop-card">
          <div class = "shop">
            <img src="<%= shop.cover_url.to_s %>" style="width:200px;height:200px">
          </div>
          <div><%= shop.id %></div>
          <div><%= shop.shop_name %></div>
          <div class="actions">
            <%= link_to("Show", {:action => 'show', :id => shop.id}, :class => 'actionshow') %>
          </div>
        </div>
      <% end %>
    <% else %>
      <div>No results were found...</div>
    <% end %>
  <% else %>
    <div>No results were found...</div>
  <% end %>    
</div>

    <!-- Items search results -->
<div class = "page">
  <div class = "search-res">Item results</div>
  <% if @items != nil %>
    <% if !@items.empty? %>
      <% @items.each do |item| %>
        <div class ="shop-card">
          <div class = "shop">
            <!-- This is where the item's image should be added -->
          </div>
          <div><%= item.id %></div>
          <div><%= item.item_name %></div>
          <div class="actions">
            <%= link_to("Show", {:controller => 'item', :action => 'show', :id => item.id, :shop_id => item.shop_id}, :class => 'actionshow') %>
          </div>
        </div>
      <% end %>
    <% else %>
      <div>No results were found...</div>
    <% end %>
  <% else %>
    <div>No results were found...</div>
  <% end %>    
</div>

app/views/shops/show.html.erb
<div class = "page", id = "page">
<div class = "show-shop", id = "show-shop">
  <div class = "shop-name"><%= @shop.shop_name %></div>
  <div class = "shop-owner">by <%= @shop.user.uname.to_s %></div>

<!--     <h4>Shop Description</h4>
    <div><%= @shop.shop_desc %></div> -->
    
    <div>
    <!-- This is the shop cover image. Can either use image_tag function or the good old html. I used html for css image resizing -->

      <img src="<%= @shop.cover_url.to_s %>" style="width:200px;height:200px" class = "shop-image"> 
    </div>
     
     
    <div class = "add2">  
    <button class = "shop-button", onclick="test()">Description</button>
    </div>
    <div class = "add1">
    <!-- Check if user is logged in -->
    <% if user_signed_in?%>
    <!-- Check if user does not own this shop -->
    <% if !current_user.shops.include?(@shop)%>
    <!-- Check if user is not already following this shop -->
    <% if !current_user.followed_shops.include?(@shop) %>
    <!-- The Follow Shop button -->
    <%= button_to("Follow Shop", {:action => 'follow', :id => @shop.id}, :class => 'shop-button') %>
    <%else%>
    <%= button_to("UnFollow Shop", {:action => 'unfollow', :id => @shop.id}, :class => 'shop-button') %>
    <%end%>
    <%end%>
    <%else%>
    <%end%></div>
  <% if user_signed_in?%>
        <% if current_user.shops.include?(@shop)%>
          <div class = "add1">
        <%= button_to("Delete", {:action => 'delete', :id => @shop.id}, :class => 'shop-button') %>
          </div>
          <div class = "add1">
          <%= button_to("Edit", {:action => 'edit', :id => @shop.id}, :class => 'shop-button') %>
          </div>
          <div class = "add1">
  <%= button_to("Add New Item", {:controller => 'item', :action => 'new', :shop_id => @shop.id}, :class => 'shop-button') %>
  </div>
        <%end%>
        <%end%>
  </div>

<div class = "shop-page">
<div id= "desc", class = "invisible"><%= @shop.shop_desc %> </div>
<!-- This is the item showcase of the shop -->
    <% if @item!=nil %>
      <% @item.each do |item| %>
          <% if item.item_attachments.first %>
            <div class="arrange_o">
              <ul class="gallery_o">
                <li><%= image_tag item.item_attachments.first.photo_url, :size => "150x250" %></li>
          <% end %></ul></div>
                  <span class="name_o">
                  <span class="title_o"><p class="art-name"> <%= item.item_name %> </p></span>
                    <%= link_to "Show",  {:controller => 'item', :action => 'show', :id => item.id}, :class => 'actionshow_o' %>
          <% if current_user!=nil %>
          <% if !current_user.shops.include?(@shop)%>
                    <%= link_to 'Add to Cart', cart_items_path(item_id: item.id) ,method: :post , :class => 'actioncart_o' %>
          <%end%>
          <%end%>
        <%if user_signed_in? and !reported?(item.id,current_user.id)%>  <!-- Can't Report An Owned Item Or Report Item Twice-->
            <% if !current_user.shops.include?(@shop)%>
                <%= link_to 'Report Item' ,{:controller => 'item', :action => 'report', :id => item.id} , :class => 'actionshow_o'%>
            <%end%>
        <%end%>
   <!--    The edit and delete buttons won't appear if the user is not signed in or doesnt own the shop -->
                      <% if user_signed_in? %>
                        <% if current_user.shops.include?(@shop)%> 
                         <%= link_to "Edit", {:controller => 'item', :action => 'edit', :id => item.id,:shop_id => @shop.id}, :class => 'actionedit_o' %> 
                          <%= link_to "Delete", {:controller => 'item', :action => 'delete', :id => item.id, :shop_id => @shop.id}, :class => 'actiondelete_o' %>   
                        <%end%>
                     <%end%>
    </span></li>
    </ul>
           </div>  
      <%end%>
    <%end%>
</div>
</div>
<script type="text/javascript">document.getElementById("show-shop").setAttribute("style","height:"+ document.getElementById("page").offsetHeight +"px;")</script>