config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :cart_items
  resources :carts
  resources :item_attachments

  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'home#index'

  get '/messages/inbox' => 'messages#inbox', as: 'inbox'
  get '/messages/sentbox' => 'messages#sentbox', as: 'sentbox'
  get '/messages/trash' => 'messages#trash', as: 'trash'
  get '/messages/new' => 'messages#new', as: 'compose'
  get '/messages/show' => 'messages#show', as: 'show'
  post '/messages/inbox' => 'messages#inbox'
  post '/messages/sentbox' => 'messages#sentbox'
  post '/messages/new' => 'messages#new'
  post '/messages/create' => 'messages#create'
  post '/messages/trash' => 'messages#trash'
  post '/messages/show' => 'messages#show'

  match '/destroy_image' => 'items#destroyImage', :as => 'destroyImage', via: [:get, :post]

  mount Commontator::Engine => '/commontator'

match ':controller(/:action(/:id))', :via  => [:get, :post , :delete]
  

end

app/models/item_attachment.rb
class ItemAttachment < ActiveRecord::Base
	
	mount_uploader :photo, PhotoUploader
	belongs_to :item
end

app/controllers/item_attachments_controller.rb
class ItemAttachmentsController < ApplicationController
  before_action :set_item_attachment, only: [:show, :edit, :update, :destroy]

  # GET /item_attachments
  # GET /item_attachments.json
  def index
    @item_attachments = ItemAttachment.all
  end

  # GET /item_attachments/1
  # GET /item_attachments/1.json
  def show
  end

  # GET /item_attachments/new
  def new
    @item_attachment = ItemAttachment.new
  end

  # GET /item_attachments/1/edit
  def edit
  end

  # POST /item_attachments
  # POST /item_attachments.json
  def create
    @item_attachment = ItemAttachment.new(item_attachment_params)

    respond_to do |format|
      if @item_attachment.save
        format.html { redirect_to @item_attachment, notice: 'Item attachment was successfully created.' }
        format.json { render :show, status: :created, location: @item_attachment }
      else
        format.html { render :new }
        format.json { render json: @item_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_attachments/1
  # PATCH/PUT /item_attachments/1.json
  def update
    respond_to do |format|
      if @item_attachment.update(item_attachment_params)
        format.html { redirect_to @item_attachment, notice: 'Item attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_attachment }
      else
        format.html { render :edit }
        format.json { render json: @item_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_attachments/1
  # DELETE /item_attachments/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.item_attachments.all.find(params[:attachment_id]).destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_attachment
      @item_attachment = ItemAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_attachment_params
      params.require(:item_attachment).permit(:item_id, :photo)
    end
end

app/views/item_attachments/_form.html.erb
<%= form_for(@item_attachment) do |f| %>
  <% if @item_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_attachment.errors.count, "error") %> prohibited this item_attachment from being saved:</h2>

      <ul>
      <% @item_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.number_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_attachments/edit.html.erb
<h1>Editing Item Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_attachment %> |
<%= link_to 'Back', item_attachments_path %>

app/views/item_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Item Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_attachments.each do |item_attachment| %>
      <tr>
        <td><%= item_attachment.item_id %></td>
        <td><%= item_attachment.photo %></td>
        <td><%= link_to 'Show', item_attachment %></td>
        <td><%= link_to 'Edit', edit_item_attachment_path(item_attachment) %></td>
        <td><%= link_to 'Destroy', item_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item attachment', new_item_attachment_path %>

app/views/item_attachments/new.html.erb
<h1>New Item Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', item_attachments_path %>

app/views/item_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @item_attachment.item_id %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @item_attachment.photo %>
</p>

<%= link_to 'Edit', edit_item_attachment_path(@item_attachment) %> |
<%= link_to 'Back', item_attachments_path %>