config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :cart_items
  resources :carts
  resources :item_attachments

  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'home#index'

  get '/messages/inbox' => 'messages#inbox', as: 'inbox'
  get '/messages/sentbox' => 'messages#sentbox', as: 'sentbox'
  get '/messages/trash' => 'messages#trash', as: 'trash'
  get '/messages/new' => 'messages#new', as: 'compose'
  get '/messages/show' => 'messages#show', as: 'show'
  post '/messages/inbox' => 'messages#inbox'
  post '/messages/sentbox' => 'messages#sentbox'
  post '/messages/new' => 'messages#new'
  post '/messages/create' => 'messages#create'
  post '/messages/trash' => 'messages#trash'
  post '/messages/show' => 'messages#show'

  match '/destroy_image' => 'items#destroyImage', :as => 'destroyImage', via: [:get, :post]

  mount Commontator::Engine => '/commontator'

match ':controller(/:action(/:id))', :via  => [:get, :post , :delete]
  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :cart_items , dependent: :destroy 
	belongs_to :user
	def total_price
		cart_items.to_a.sum { |item| item.total_price }
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	#used for the view index
	def index
		if (current_user)  #checks if a user is logged in
			@cart = current_cart
			render 'carts/index'
		else        # else create a temporary cart
			@cart =	temporary_cart
			@cart.each do |cartItem|
				cartItem[1][5] = cartItem[1][1].to_i * cartItem[1][3].to_i
			end
			@totalPrice = 0
			@cart.each do |cartItem|
				@totalPrice += cartItem[1][5].to_i
			end
			render 'carts/temporary_cart'
		end
	end

	#update cart_item Quantities in temporary cart
	def update_quantity
		item_id = params[:cart_item_id]
		if (cart_params[:quantity].to_i > temporary_cart[item_id][4])
			flash[:error] = 'Cannot Order with quantity higher than the available in stock.'
		else
			flash[:notice] = 'Cart Updated'
			temporary_cart[item_id][1] = cart_params[:quantity]
		end
		redirect_to :back
	end

	#delete cart_item from Cart (temporary cart)
	def remove_item
		item_id = params[:cart_item_id]
		temporary_cart.delete(item_id)
		redirect_to :back
	end

	#delete the cart from the database
	def destroy
		if(current_user)	 # check if user is sign_in to delete the cart id from the database or not
			cart = current_cart
			Cart.destroy(cart)	 # destroy in database
		else
			session[:temporary_cart] = nil
		end
		flash[:notice] = "Your Cart Is Clear."
		redirect_to root_path
	end
	#allows the quantity field
	private 
	def cart_params
		params.require(:cart).permit(:quantity)
	end

end

app/views/carts/index.html.erb
<html>
<body>
<%if @cart.cart_items.empty?%> <!--checks if the cart is empty-->
			<div class="content-helper">
				 <h2 class="empty-cart"> Your Cart Is Empty </h2>
			</div>
			<%=button_to 'Go To Shops' , {:controller => '/shops' , method: :get}, class: 'shops' %>

		<%else%>
				<%= button_to 'Clear Cart' , cart_path(@cart) , method: :delete , class: 'clear'%>
			<!--CLEAR BUTTON-->
			<button class="checkout" onclick="myFunction()"><a>Checkout</a></button> 

			<%=button_to 'Continue Shopping' , {:controller => '/shops' , method: :get}, class: 'Continue' %>
	 <!-- Continue BuTTON -->
			<script>
					function myFunction() {
   						 var addres = prompt("Please enter your addres", "Home");
    
   								 if (addres != null) {
      							  location.href = "/home";
	    								}
									}
									</script>

		<%end%>
		 <!-- CHECKOUT BuTTON -->

			
<div class="content-helper"><!--Big Container-->
		<%@cart.cart_items.each do |cart_item|%> <!--List All Cart Items-->
		
		<%if cart_item.item.item_attachments.first %>
			<div class="item-image"> <%=image_tag(cart_item.item.item_attachments.first.photo_url, size: "190x90")%> 
			</div>
			<%else%>
					<div class="item-image"><img  src="https://www.cs-cart.com/images/thumbnails/5/120/facebook_store_product_v1.png" width="90" ></div>
			<%end%>
				
			
				<label class="item-label">Item Name: </label>
					<label class="item-title"><%=cart_item.item.item_name%></label>
					<%= form_for :cart_item , :url => { :controller => 'CartItems' , :action => "update_quantity" , :cart_item_id => cart_item.id } do |f|%>
					<label class="item-label">Quantity:</label><%= f.text_field :quantity , class:'text-field' , value: cart_item.quantity %><span class="complete">x </span><span class="price"><span class="price">$</span><%=cart_item.item.price%></span> <span class="complete"> = </span><span class="price">$</span><span class="price"> <!--Price -->
								<%= cart_item.total_price %>
								</span>
	<!--Update Button--><%= f.submit 'Update' , class: 'update'%>
						<%end%>
    <!--Delete Button--><%=button_to 'Delete' ,{controller: 'CartItems' , action: :destroy , cart_item_id: cart_item.id}, class: 'delete' , method: :delete%>

<!--Item Description-->	<label class="item-label">Description: </label>
						<span class="item-desc"><%= cart_item.item.description%></span>
						<br>
<!--Item Quantity-->	<label class="item-label">Quantity In Stock: </label>
						<span class="price"><%= cart_item.item.quantity%></span>
						<hr>
		<%end%>	
		<%if !@cart.cart_items.empty?%>
					<div class="total-price"> <!--Total Price-->
						<strong><span class="complete">Total cost: </span></strong><span class="price">$</span><span class="price"><%=@cart.total_price%></span>
					</div>
		<%end%>			
	</div>
		
</body>
</html>

app/views/carts/temporary_cart.html.erb
<html>
<body>
	<%if @cart.empty?%><!--checks if the cart is empty-->
			<div class="content-helper">
				 <h2 class="empty-cart"> Your Cart Is Empty </h2>
			</div>	
			<%=button_to 'Go To Shops' , {:controller => '/shops' , method: :get}, class: 'shops' %>
		<%else%>
			<%= button_to 'Clear Cart' , {action: :destroy} ,  method: :delete , class: 'clear'%>
			<!--CLEAR BUTTON-->
			<%=button_to 'Continue Shopping' , {:controller => '/shops' , method: :get}, class: 'Continue' %><!-- Continue BuTTON -->

			<button class="checkout" onclick="myFunction()">Checkout</button> 
			<script>
				function myFunction() {
    				alert("You Must LogIn First");
    				location.href = "/users/sign_in";
					}
			</script>
			<!-- CHECKOUT BuTTON -->
		<%end%>
		
<div class="content-helper"><!--Big Container-->
		<%@cart.each do |cart_item|%><!--List All Cart Items-->
			<%if cart_item[1][6] %>
					<div class="item-image"> <%=image_tag(cart_item[1][6], size: "190x90")%> 
					</div>
			<%else%>
					<img  src="https://www.cs-cart.com/images/thumbnails/5/120/facebook_store_product_v1.png" width="90" >
			<%end%>
		
				<label class="item-label">Item Name: </label>
					<label class="item-title"><%=cart_item[1][0]%></label>
					<%= form_for :cart , :url => { :controller => 'Carts' , :action => "update_quantity" , :cart_item_id => cart_item[0] } do |f|%>
					<label class="item-label">Quantity:</label><%= f.text_field :quantity , class:'text-field' , value: cart_item[1][1] %> <span class="complete">x </span><span class="price"><span class="price">$</span><%=cart_item[1][3]%></span> <span class="complete"> = </span><span class="price">$</span><span class="price"> <!--Price -->
								<%= cart_item[1][5] %>
								</span>
	<!--Update Button--><%= f.submit 'Update' , class: 'update'%>
						<%end%>
	<!--Delete Button--><%=button_to 'Delete' ,{controller: 'Carts' , action: 'remove_item' , cart_item_id: cart_item[0]}, class: 'delete' , method: :delete%>

<!--Item Description-->	<label class="item-label">Description: </label>
						<span class="item-desc"><%= cart_item[1][2]%></span>
						<br>
	<!--Item Quantity--><label class="item-label">Quantity In Stock: </label>
						<span class="price"><%= cart_item[1][4]%></span>

		<hr>
		<%end%>
		<%if !@cart.empty?%>
			<div class="total-price"><!--Total Price-->
				<strong><span class="complete">Total cost: </span></strong><span class="price">$</span><span class="price"><%=@totalPrice%></span>
		</div>
		<%end%>
	</div>	
</body>
</html>